### ISSUE TITLE
No src folder

### ISSUE THREAD

**Issue by ghost** [McKay42/McOsu-NX#4]
Makefile references the source files from a folder called src but that folder is not present in this repo.

**Comment by ghost** [comment]
nvm it requires the engine too, sorry

**Comment by McKay42** [comment]
The current build process is a bit convoluted since I haven't cleaned it up completely, you will also need to merge the custom [SDL Mixer X](https://github.com/WohlSoft/SDL-Mixer-X) variant of libSDL2_mixer into your `/<devkitpro>/portlibs/switch/lib/` as well as add the header file to `/<devkitpro>/portlibs/switch/include/` (you can find these files in the engine libraries folder for horizon).

Since I'm not uploading game resources (images, sounds, skins), you'll have to either get them from the Steam version or extract the nro build.

**Comment by McKay42** [comment]
Oh and the newest version of switch-sdl2-2.0.8-16 breaks audio completely, you have to use switch-sdl2-2.0.8-15 currently.
